### ISSUE TITLE
Option[BigDecimal] issue

### ISSUE THREAD

**Issue by riccardo14** [julianpeeters/avrohugger#107]
Hi

I'm trying to generate a Scala case class from the following avro schema with `avroScalaGenerateSpecific`:

```json
{
  "type": "record",
  "name": "schema_test",
  "namespace": "com.example",
  "fields": [
    {
      "name": "ciao",
      "type": [
        "null",
        {
          "type": "bytes",
          "scale": 5,
          "precision": 64,
          "logicalType": "decimal"
        }
      ],
      "default": null
    }
  ]
}
```

but the tool does not generate decimalConversion and it gives me error.

Any help?

Riccardo

**Comment by julianpeeters** [comment]
Hi @riccardo14 ,thanks for the report and example schema, I can indeed get an error with a similar schema. I believe that at least one cause is [here](https://github.com/julianpeeters/avrohugger/blob/master/avrohugger-core/src/main/scala/format/specific/converters/JavaConverter.scala#L73), the implementation only supports simple decimals. I can probably find time to look a bit closer this weekend and next.

**Comment by riccardo14** [comment]
Thanks @julianpeeters

**Comment by lazyval** [comment]
~What if instead of referencing (missing?) decimal conversion from generated class, we could just use https://github.com/apache/avro/blob/master/lang/java/avro/src/main/java/org/apache/avro/Conversions.java#L62-L127 instead?~
So it's the way it actually happens for non-nullable BigDecimals already, but method is not generated for companion object when it's nullable. I see.
