### ISSUE TITLE
Generated case classes extend custom trait

### ISSUE THREAD

**Issue by z4f1r0v** [julianpeeters/avrohugger#113]
Hello,

Is it possible to define a custom trait that the generated case classes can extend?

I think that this [was](https://github.com/julianpeeters/avrohugger/issues/80) the case but then now isn't.

Thanks for the help!

**Comment by julianpeeters** [comment]
Hi @alexanderzafirov,

Not arbitrary custom traits (there's no plan to support that), but a trait that is named after the protocol, so that records form an ADT. As that linked issue states, the feature is now opt-in. If that's what you're looking for, check the readme and please let me know if something unclear.

**Comment by z4f1r0v** [comment]
Thank you for you comment @julianpeeters! 
Yes, what you described is what I am looking for. I've been looking through the documentation and I tried on my own, and I am not able to achieve what I want. How can I define several `.avsc` files that I can then form an ADT with? 

```
@namespace("com.a.b")
protocol Foo {
   import schema "A.avsc";
   import schema "B.avsc";
}
```
Gives me a `(Compile / avroScalaGenerate) java.util.NoSuchElementException: key not found:` exception.

**Comment by julianpeeters** [comment]
@alexanderzafirov thanks for the report; sorry you ran into that.

I'm not sure off the top of my head, but it looks like, if nothing else, that error can be improved.

I'm a little short on time for customer support however, so I warn that you may like to investigate a more mature project.

If you'd like to get help on this for avrohugger, looks like the following could help:
1. Minimum runnable example, please
2. Do we expect your schema to be parsable? Does it work if you use apache avro to compile?
3. Simplify. Does it do what you expect when the files aren't imported?
4. searching for `java.util.NoSuchElementException: key not found` in this project (and I see you're using the plugin, so that project too), it seems like there's still an open issue regarding sorting imported schema files -- sounds like this could be what you're hitting: https://github.com/julianpeeters/avrohugger/issues/61
5. With (4) in mind, search for imports, is this your issue?https://github.com/julianpeeters/sbt-avrohugger/issues/68

**Comment by z4f1r0v** [comment]
@julianpeeters Thank you for your help. 
I discovered that I am not going to be able to use the ADT functionality since I can only work with `.avsc` files.
I am closing this issue.
