### ISSUE TITLE
Read comments from IDLs

### ISSUE THREAD

**Issue by mariussoutier** [julianpeeters/avrohugger#21]
Avro supports Javadoc-style comments in IDL files:

https://avro.apache.org/docs/1.7.7/idl.html#minutiae_comments

**Comment by julianpeeters** [comment]
This would certainly be nice. Avrohugger has no support for docs at all yet, would be nice to read doc fields and write them as comments in case class definitions as well. I think I can give this a shot this weekend.

**Comment by julianpeeters** [comment]
I finally got around to this for version 0.8.0 (sbt-avrohugger 0.7.0).

I may have gone a little overboard: in addition to routing idl comments to schema doc attributes, all schema doc attributes (record and field) become ScalaDocs to the generated classes. Also, for generic case class to specific case class generation, ScalaDocs become Avro schema doc attributes. Feedback welcome, of course.

**Comment by mariussoutier** [comment]
Nice - works like a charm! Thank you!

**Comment by mariussoutier** [comment]
Only small suggestion: if no comment is given, currently it is generating `@param productCode null`, you could leave out the null part.

**Comment by mariussoutier** [comment]
Another thing I noticed is when the record has no comment, but its members have, no doc is generated.

**Comment by julianpeeters** [comment]
Ah, I see, much thanks for the eyes and the failing cases. I'll get a fix out tonight. I also notice that Treehugger is producing JavaDocs (not ScalaDocs like I had expected), which will have too suffice here too, at least until I figure out what, if anything, Treehugger wants to do about that.

**Comment by mariussoutier** [comment]
Mh, what do you mean, what is the difference between JavaDocs and ScalaDocs comments?

**Comment by julianpeeters** [comment]
Relatively minor difference it seems. [ScalaDoc link](http://docs.scala-lang.org/style/scaladoc.html). I only see two relevant differences: 

1) comments always start on the first line
2) line-initiating asterisks align in the 3rd column rather than the 2nd.

I figure most parsers will be able to handle either, although I suppose some JavaDoc parsers may cut off the first line?

**Comment by julianpeeters** [comment]
Oh, and for comparison [here](http://eed3si9n.com/treehugger/comments.html#Scaladoc+style+comments)'s the docs that Treehugger is producing.

If those docs are tolerable, you can try avrohugger 0.8.1 (sbt-avrohugger 0.7.1), and I'll work with Treehugger ASAP to come to some conclusion.

**Comment by mariussoutier** [comment]
I think even IntelliJ does it JavaDoc-style then.

**Comment by mariussoutier** [comment]
Works great I think! The last task would be to enable this for generic records as well.

**Comment by julianpeeters** [comment]
OK great.

Hilarious Scala trivia. I'm also amused by the ScalaDoc link above, which offers what I take to be a prototypical example of a ScalaDoc. Yet, it is displayed in html of course, and so the trailing whitespace is truncated, which, according to many, is a good thing (including aggressive text editors!), but, buried in a small link, is an ancient but explicit spec dictating trailing spaces! And really, who can we even get to stop their busy days and care about docs? Slapstick :)

But I'm happy to get this working for generic records, but I don't see the error?

So far the changes I've made have not been peculiar to the SpecificRecord format, and the tests show that docs are working both for them and for generated case classes that don't extend SpecificRecordBase (what I had called a 'Standard' case class format, but I agree should probably be renamed to 'Generic' in order to conform with Avro's naming conventions).bPerhaps a directory needs to be cleared on your end? Otherwise point me in right direction and I'll likely be able to get on it this week.

**Comment by mariussoutier** [comment]
LOL. The generated ScalaDoc pages also don't work on mobile (e.g. iPad), which I reported as a bug a couple of years ago. Still not fixed :)

**Comment by mariussoutier** [comment]
Re: Generic - you are right, I was actually looking at the wrong class in the wrong project (I'm generating SpecificRecords for the JVM model, and generic case classes for the Scala.js model, and one record exists twice in two different AVDLs, so there's four places to look and I picked exactly the wrong one 😡).

**Comment by mariussoutier** [comment]
Hmm... I am however seeing a stack overflow error. I will open a separate ticket.
