### ISSUE TITLE
Creating an enum within protocol fails due to (unnecessary?) base types of protocol trait

### ISSUE THREAD

**Issue by stephendrew** [julianpeeters/avrohugger#37]
Creating an enum within a protocol generates code that does not compile.  

``` scala
sealed trait MyProtocol extends Product with Serializable

final object MyEnum extends Enumeration with MyProtocol {
  type MyEnum = Value
  val A, B = Value
}
```

```
Error:(6, 14) object creation impossible, since:
it has 3 unimplemented members.
/** As seen from object MyEnum, the missing signatures are as follows.
 *  For convenience, these are usable as stub implementations.
 */
  // Members declared in scala.Equals
  def canEqual(that: Any): Boolean = ???

  // Members declared in scala.Product
  def productArity: Int = ???
  def productElement(n: Int): Any = ???
final object MyEnum extends Enumeration with MyProtocol {
             ^
```

It would be a nice option to be able to generate an enum as a sealed trait with case objects.

**Comment by julianpeeters** [comment]
I see, sorry for the troubles. You're right, looks like Avrohugger is extending root traits with parents that are not shared by all of its subtypes. I expect to have time for a fix this weekend. Much obliged for the report.

> It would be a nice option to be able to generate an enum as a sealed trait with case objects.

Sure thing. I'll track this as part of a [similar issue](https://github.com/julianpeeters/sbt-avrohugger/issues/18).

**Comment by StephenDrewLDS** [comment]
Hey Julian,
I wanted to submit a pull request that at the very least removed the unnecessary base types.  Following your guidelines of running the tests, but they are very slow, CPU intensive.  My machine isn't that shabby I thought?  Am I doing something wrong? 

```
sbt scripted
```

The only test it has run in 20 minutes or so is "tool descriptions should fit in 80 characters"

Regards,
Steve

**Comment by julianpeeters** [comment]
Sorry for the delay, and thanks for the attention to getting this fixed.

The `scripted` tests are intensive, but that seems excessive. I've fixed a bug in the testing utils since your fork, I'm afraid that it might have been the [culprit](https://github.com/StephenDrewLDS/avrohugger/blob/master/avrohugger-tools/src/test/scala/Util.scala#L36). Reading files was not very robust, so I added some retries, but apparently only caught one class of error, so it used to hang when there was any other error and I had just gotten "lucky" in testing.

I still need to add some more tests before release, but I expect that you shall find the enum issue fixed in 0.11.0-SNAPSHOT if you want to clone and publish this (and maybe the updated plugin) locally.

**Comment by StephenDrewLDS** [comment]
Thanks Julian - I'll give it a go today.  

Running `sbt publishLocal` also hangs, in the tests again I think.

![image](https://cloud.githubusercontent.com/assets/17161514/16142557/f0298774-346e-11e6-96bb-310883207497.png)

**Comment by julianpeeters** [comment]
I didn't see the screenshot until now. Is this still failing to publish for you? Seems to work ok for me now, but I'd like to try to track down the issue if this is still a problem. Note that sbt plugins can only use Scala 2.10, so `+ publish-local` will be required to publish both cross-versions. I expect the compilation to take < 10 seconds, the test < 1 min, the scripted tests < 15 min, the avrohugger-tools jar is huge and so publishing it takes < 3 min.

---

Also, do you have a preference as to how the case object enum is represented? I like the simplicity of a plain sealed trait and some objects: 

``` scala
sealed trait EnumStyle
case object Style1 extends EnumStyle
```

But I also would like to be careful of namespace pollution, so I am leaning towards putting the case objects in a companion object: 

``` scala
sealed trait EnumStyle
object EnumStyle {
  case object Style1 extends EnumStyle
}
```

Would the companion style work okay for you?

**Comment by julianpeeters** [comment]
Hmm, looks like Avro4s is choking on companion style case object enums, may have to settle for the plain sealed trait.

**Comment by StephenDrewLDS** [comment]
I'd have probably preferred the second option, but whatever works is good. Haven't had a chance to re-run the publish, but if I can't get it to work I'll let you know. Thanks.

**Comment by julianpeeters** [comment]
Ok, I appreciate the feedback.

I prefer the second option as well - would like to find a solution that is maximally useful as well as compatible.

What is your use case with the Standard format? Presumably you are deserializing into Scala, or serializing from Scala, but what tool are you using for the serialization? Plain Apache Avro's GenericRecord API, or a library like Scalavro or Avro4s? Since enums of the second option work fine with the GenericRecord API, I'm again favoring it with a warning about how some libraries can't. Sounds like you'd prefer this as well?

**Comment by StephenDrewLDS** [comment]
avro4s at the moment, with probability to need GenericRecord later.

**Comment by julianpeeters** [comment]
You may like to try avrohugger and sbt-avrohugger version 0.11.0, which should have synced up with maven central by now.

Regarding the case object enums, I went with the second option, the companion style, since they offer a more pleasant api, and both styles ended up giving me trouble with avro4s in the tests. So I don't intend to push you towards using GenericRecord, but is the only thing that works for me with case object enums.

Oh, and just to be clear for the record about the motivation behind having the sealed trait extend what all its members extend, it's for type inference in certain libraries that depend on it.

Cheers
