### ISSUE TITLE
Generate Scala 2.12 compatible classes

### ISSUE THREAD

**Issue by robvadai** [julianpeeters/avrohugger#65]
Despite the README says generated classes are Scala 2.12 compatible, I got this error when using generated case classes in a Scala 2.12 project: `java.lang.NoClassDefFoundError: scala/Product$class`.
The avrohugger dependency is only available for Scala 2.11 so when I build my JAR I can't use the Scala 2.12 compiler in the same project. I want to use the same project to generate Scala source code and compile and build a JAR of classes.

**Comment by julianpeeters** [comment]
Hi Rob, sorry you ran into issues, and thanks for the report.

>Despite the README says generated classes are Scala 2.12 compatible, I got this error when using generated case classes in a Scala 2.12 project: java.lang.NoClassDefFoundError: scala/Product$class.

I expect the generated classes to be compatible with 2.12, so I suspect your issue here is likely [this](https://github.com/julianpeeters/avrohugger/issues/47)(only Avro reserved words are taken into account, Scala reserved words are not respected). If this is not your issue, please provide a minimized project and/or schema so that I may reproduce the error.

Avrohugger for Scala 2.12 is still a TODO.

I'm a bit busy currently, so please expect a "months" timeframe for fixes. PRs welcome of course!

**Comment by robvadai** [comment]
Hi there,

I have no issues with Scala 2.11 so I'm not sure if it's a naming conflict.
I tried to upgrade the library to Scala 2.12 but the dependency `"com.eed3si9n" %% "treehugger"` doesn't have artifacts with this version. When I tried to upgrade that library as well I ran into the issue that their [sbt-pamflet](https://github.com/eed3si9n/treehugger/blob/master/project/pf.sbt) dependency is not published anywhere.

**Comment by julianpeeters** [comment]
> I have no issues with Scala 2.11 so I'm not sure if it's a naming conflict.

Hmm, I don't know then, but thanks for checking. Looking back at my tests, I think that I may have indeed forgotten to test the full `scripted` suite on 2.12 (I think I've only tested the string representations of the generated types, but may have only compiled a few, yet extrapolated those successes). I haven't heard any other negative reports like this however, so from ignorance, there is still room in my mind for the possibility that its your build system (I think most people are either using avrohugger-tools, or one of the plugins, sbt- or maven-, no manual packaging of jars that I know of).

I've had success fixing issues with Treehugger by publishing pamflet locally. IIRC there will be one other  annoying-but-resolvable hangup if you go that route. I don't recall how treehugger piggybacks off of scalac -- I expect upgrading it to produce code for 2.12 will either be really easy or really hard.

One last roadblock that comes to mind (and which may be the end of the road for now, I'm afraid) is that I don't believe avrohugger will be able to cross-compile both 2.10 and 2.12 (due to a deprecation of `termName` or something like that), yet it won't be able to drop support for 2.10 until sbt itself moves off of 2.10 for sbt 1.0 (currently in beta). For now, avrohugger needs to publish a 2.10 so that the sbt-avrohugger plugin can use it in sbt 0.13, which is still on 2.10.

**Comment by robvadai** [comment]
Got it thanks. I'm using Gradle as my build tool that's why I'm using this library and not the sbt plugin.

**Comment by fkoehler** [comment]
We also need a Scala 2.12 and sbt 1.0 release

**Comment by julianpeeters** [comment]
@robvadai @fkoehler Thanks for your patience, all. avrohugger 0.17.0 for scala 2.12 (and sbt-avrohugger 1.0.0) is out now.
