### ISSUE TITLE
Replace LocalDateTime with Instant

### ISSUE THREAD

**Issue by diesalbla** [julianpeeters/avrohugger#93]
This issue concerns the support for the Logical Avro type `timestamp_ms`. 

At present, the avrohugger maps the logical avro type `timestamp_ms` to the   [`java.date.LocalDateTime` Java class](https://docs.oracle.com/javase/8/docs/api/java/time/LocalDateTime.html). We propose that, instead, the `timestamp_ms` logical type should be mapped to the [`java.time.Instant` Java class](https://docs.oracle.com/javase/8/docs/api/java/time/Instant.html).

The Avro logical type `timestamp_ms` is described in the [specification](https://avro.apache.org/docs/1.8.2/spec.html#Timestamp+%28millisecond+precision%29) as follows: 
> [...] represents an instant on the global timeline [...] annotates an Avro long, where the long stores the number of milliseconds from the unix epoch, 1 January 1970 00:00:00.000 UTC. 

This corresponds directly with the description of the `java.time.Instant` class, which says: 
> This class models a single instantaneous point on the time-line. This might be used to record event time-stamps in the application. [...] The epoch-seconds are measured from the standard Java epoch of 1970-01-01T00:00:00Z 

The `LocalDateTime` class is described in the documentation as serving a different purpose, more related to the human-readable descriptions of dates: 
> A date-time without a time-zone in the ISO-8601 calendar system.
> LocalDateTime is an immutable date-time object that represents a date-time, often viewed as year-month-day-hour-minute-second. This class does not store or represent a time-zone. [...] It cannot represent an instant on the time-line without additional information such as an offset or time-zone. 

### Related Issues

Support for the logical `timestamp_ms` type was introduced in PR #87 by @raulraja, and a change to generate the converters is currently submitted in PR #88.

**Comment by raulraja** [comment]
@julianpeeters @diesalbla wanted to leave for the record that I'm in favor for this change and I agree that `Instant` is closer to the avro semantics for `timestamp_ms`

**Comment by julianpeeters** [comment]
Ok great, thanks for tracking that down @diesalbla @raulraja, I agree with the replacement. My queue is getting a it full however, looking ~2wks out, tho I'll try to give this some priority.

**Comment by julianpeeters** [comment]
#88 is still WIP (now labeled), so my current plan is to focus on updating the changes from #87. This way the update to `Standard` format can be released while the work for `SpecificRecord` continues.

**Comment by julianpeeters** [comment]
It looks like avro4s supports LocalDateTime but not Instant https://github.com/sksamuel/avro4s#type-mappings (I noticed because there are some serialization tests in sbt-avrohugger that use avro4s which failed `sbt:sbt-avrohugger> scripted avrohugger/GenericSerializationTests`). Is the plan to submit PR to avro4s? Alternatively we could make it configurable, so users could use one for avro4s and the other for java avro's Generic API.

**Comment by diesalbla** [comment]
This issue https://github.com/sksamuel/avro4s/issues/207 mentions some partial support for `java.time.Instant` in `avro4s`. 

One problem that I can see for `avro4s` is that the Java type `Instant` can be mapped to two Avro logical types: [timestamp-micros](http://avro.apache.org/docs/1.8.2/spec.html#Timestamp+%28microsecond+precision%29) and [timestamp-millis](http://avro.apache.org/docs/1.8.2/spec.html#Timestamp+%28millisecond+precision%29).

**Comment by julianpeeters** [comment]
Thanks for the issue link, I'd missed that.

Freestyle needs avro4s compatibility, correct? It's not just the scripted tests that need it? 

I'm fairly opposed to adding avro4s-specific code the generated classes, avrohugger should just generate plain old case classes for this use case IMO.




I see what you mean about `Instant` mapping to two logical types: e.g. if we have class generated from a schema with `timestamp-micros`, avro4s may serialize that class by generating a schema with `timestamp-millis`, or vice versa, and then the schemas wouldn't match (Paul Snively raised this as a possible issue, but at the time we hadn't identified a place where our data-first schema and avro4s's generated schema could diverge).

A solution to this could be to add a method to avro4s that serialized according to a schema we passed it (perhaps every case class could store its schema in its companion object), instead of having avro4s generated the schema on the fly (like it does currently)

**Comment by diesalbla** [comment]
> Freestyle needs avro4s compatibility, correct? It's not just the scripted tests that need it?

`freestyle-rpc` uses `avro4s` for marshalling and unmarshalling from Avro. However, for those types not directly supported by `avro4s`, it defines its own instances, as you can see [here](https://github.com/frees-io/freestyle-rpc/blob/v0.14.0/modules/internal/src/main/scala/encoders.scala#L78-L180) 

> I'm fairly opposed to adding avro4s-specific code the generated classes, avrohugger should just generate plain old case classes for this use case IMO.

I understand, and agree, that `avrohugger` should be only about code generation, not marshalling-unmarshalling. Would you accept adding the needed marshalers to the tests for `sbt-avrohugger`?

**Comment by julianpeeters** [comment]
>  Would you accept adding the needed marshalers to the tests for sbt-avrohugger

yep! nice solution
